sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness & Gym
sonar.sources=ACEest_Fitness.py
sonar.tests=tests
sonar.python.version=3.11
sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness and Gym
sonar.sources=app,ACEest_Fitness.py
sonar.tests=tests
sonar.python.version=3.12
